; ============================================================
; platformio.ini — Estación Meteorológica IoT con FreeRTOS
; Hardware: ESP32-S3 DevKitM-1
; Framework: Arduino
; ============================================================
 
[env:esp32-s3-devkitm-1]
platform  = espressif32
board     = esp32-s3-devkitm-1
framework = arduino
 
; Velocidad del monitor serie
monitor_speed = 115200
 
; Flags de compilación
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_FREERTOS_HZ=1000
    -DBOARD_HAS_PSRAM
 
; Librerías necesarias
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
 
; Partición con OTA (opcional pero recomendado)
board_build.partitions = default_8MB.csv